config/routes.rb
Rails.application.routes.draw do
    devise_for :applicants
  resources :applicant_person_qualification_field_of_studies

    root :to => 'welcome#index'
  get 'applicants/index'
  get 'admin/main'
 get "admin/documents"
 get "admin/confirm"
 get "admin/DocumentsAdmin"
 get "documents/index"
  #get 'welcome/index'
  resources :applicant_emergency_contacts
  resources :applicant_disability_types
  resources :applicant_licenses
  resources :applicant_foi_programs
  resources :applicant_addresses
  resources :applicant_personal_details
  resources :applicant_field_of_studies
  resources :applicant_experiences
  resources :applicant_references

end

app/models/applicant_person_qualification_field_of_study.rb
class ApplicantPersonQualificationFieldOfStudy < ApplicationRecord
	belongs_to :applicant
	belongs_to :applicant_university
	belongs_to :applicant_qual_status
	belongs_to :applicant_nqf_qualification
	has_many :admin
end

app/controllers/applicant_person_qualification_field_of_studies_controller.rb
class ApplicantPersonQualificationFieldOfStudiesController < ApplicationController
  before_action :set_applicant_person_qualification_field_of_study, only: [:show, :edit, :update, :destroy]

  # GET /applicant_person_qualification_field_of_studies
  # GET /applicant_person_qualification_field_of_studies.json
  def index
    @applicant_person_qualification_field_of_studies = current_applicant.applicant_person_qualification_field_of_studies.all
  end

  # GET /applicant_person_qualification_field_of_studies/1
  # GET /applicant_person_qualification_field_of_studies/1.json
  def show
  end

  # GET /applicant_person_qualification_field_of_studies/new
  def new
    @applicant_person_qualification_field_of_study = current_applicant.applicant_person_qualification_field_of_studies.build
  end

  # GET /applicant_person_qualification_field_of_studies/1/edit
  def edit
  end

  # POST /applicant_person_qualification_field_of_studies
  # POST /applicant_person_qualification_field_of_studies.json
  def create
    @applicant_person_qualification_field_of_study = current_applicant.applicant_person_qualification_field_of_studies.build(applicant_person_qualification_field_of_study_params)

    respond_to do |format|
      if @applicant_person_qualification_field_of_study.save
        format.html { redirect_to applicant_person_qualification_field_of_studies_url, notice: 'Applicant person qualification field of study was successfully created.' }
        format.json { render :show, status: :created, location: @applicant_person_qualification_field_of_study }
      else
        format.html { render :new }
        format.json { render json: @applicant_person_qualification_field_of_study.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applicant_person_qualification_field_of_studies/1
  # PATCH/PUT /applicant_person_qualification_field_of_studies/1.json
  def update
    respond_to do |format|
      if @applicant_person_qualification_field_of_study.update(applicant_person_qualification_field_of_study_params)
        format.html { redirect_to applicant_person_qualification_field_of_studies_url, notice: 'Applicant person qualification field of study was successfully updated.' }
        format.json { render :show, status: :ok, location: @applicant_person_qualification_field_of_study }
      else
        format.html { render :edit }
        format.json { render json: @applicant_person_qualification_field_of_study.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applicant_person_qualification_field_of_studies/1
  # DELETE /applicant_person_qualification_field_of_studies/1.json
  def destroy
    @applicant_person_qualification_field_of_study.destroy
    respond_to do |format|
      format.html { redirect_to applicant_person_qualification_field_of_studies_url, notice: 'Applicant person qualification field of study was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_applicant_person_qualification_field_of_study
      @applicant_person_qualification_field_of_study = ApplicantPersonQualificationFieldOfStudy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def applicant_person_qualification_field_of_study_params
      params.require(:applicant_person_qualification_field_of_study).permit(:Field_Of_Study, :Start_Date, :End_Date, :applicant_id, :applicant_university_id, :applicant_qual_status_id, :applicant_nqf_qualification_id)
    end
end

app/helpers/applicant_person_qualification_field_of_studies_helper.rb
module ApplicantPersonQualificationFieldOfStudiesHelper
end

app/views/applicant_person_qualification_field_of_studies/_form.html.erb
<%= simple_form_for(@applicant_person_qualification_field_of_study) do |f| %>
  <%= f.error_notification %>
  <% if @applicant_person_qualification_field_of_study.errors.any? %>
    <%= @applicant_person_qualification_field_of_study.errors.full_messages %>
  <% end %>
  <div class="form-inputs">
    <%= f.input :Field_Of_Study %>
    <%= f.input :Start_Date, label: "Start Date", start_year: Time.now.year - 50, order: [:day, :month, :year] %>
    <%= f.input :End_Date, label: "End Date", start_year: Time.now.year - 50, order: [:day, :month, :year] %>
    <label>Qualification</label>
    <%= f.collection_select(:applicant_nqf_qualification_id, ApplicantNqfQualification.all, :id, :Qualification_Name, {:include_blank=>true}, {:class=>'form-control'}) %>
    <label>Qualification Status</label>
    <%= f.collection_select(:applicant_qual_status_id, ApplicantQualStatus.all, :id, :Qualification_Status, {:include_blank=>true}, {:class=>'form-control'}) %>
    <label>University</label>
    <%= f.collection_select(:applicant_university_id, ApplicantUniversity.all, :id, :University_Name, {:include_blank=>true}, {:class=>'form-control'}) %>
  </div><br>

  <div class="form-actions">
    <%= f.button :submit, "Submit", class: "btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/applicant_person_qualification_field_of_studies/edit.html.erb
<h1>Editing Applicant Person Qualification Field Of Study</h1>

<%= render 'form', applicant_person_qualification_field_of_study: @applicant_person_qualification_field_of_study %>

<%= link_to 'Show', @applicant_person_qualification_field_of_study %> |
<%= link_to 'Back', applicant_person_qualification_field_of_studies_path %>

app/views/applicant_person_qualification_field_of_studies/index.html.erb
<div class="col-xs-12 col-md-8 col-md-offset-2">
  <% if !@applicant_person_qualification_field_of_studies.any? %> 
    <%= render 'layouts/incomplete' %>
  <% end %>
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h1 class="text-center"><%= current_applicant.username %>'s Qualifications</h1>
    </div>
    <div class="panel-body">

      <% @applicant_person_qualification_field_of_studies.each do |applicant_person_qualification_field_of_study| %>
        <div class="well text-center col-xs-12 col-md-8 col-md-offset-2">
          
          <h5 class="text-primary">Qualification</h5><%= applicant_person_qualification_field_of_study.applicant_nqf_qualification %>
        <h5 class="text-primary">Field of study</h5><%= applicant_person_qualification_field_of_study.Field_Of_Study %>
        <h5 class="text-primary">University</h5><%= applicant_person_qualification_field_of_study.applicant_university %>
        <h5 class="text-primary">Start date</h5><%= applicant_person_qualification_field_of_study.Start_Date %>
        <h5 class="text-primary">End date</h5><%= applicant_person_qualification_field_of_study.End_Date %><hr>
          <%= link_to 'Edit Entry', edit_applicant_person_qualification_field_of_study_path(applicant_person_qualification_field_of_study), class: "btn btn-xs btn-warning" %>
          <%= link_to 'Destroy Entry', applicant_person_qualification_field_of_studies_path, method: :delete, data: { confirm: 'Are you sure you want to delete this entry?' }, class: "btn btn-xs btn-danger" %>
        </div>
      <% end %>


      <br>
      <div class="col-xs-12 col-md-12">
        <%= link_to 'New Applicant Qualification', new_applicant_person_qualification_field_of_study_path, class: "btn btn-block btn-primary" %><br>
        <% if @applicant_person_qualification_field_of_studies.any? %> 
          <%= link_to 'Next Step', applicant_experiences_url, class: "btn btn-block btn-success" %>
        <% end %>
      </div>
    </div>
    <br><%= link_to 'Back', root_url, class: 'btn btn-xs btn-danger' %>
  </div>
</div>

app/views/applicant_person_qualification_field_of_studies/new.html.erb
<div class="col-xs-12 col-md-8 col-md-offset-2">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h1 class="text-center">New Qualification </h1>
		</div>
		<div class="panel-body">	
			<%= render 'form', applicant_person_qualification_field_of_study: @applicant_person_qualification_field_of_study %>
		</div>	
			<%= link_to 'Back', applicant_person_qualification_field_of_studies_path, class: "btn btn-xs btn-danger" %>
	</div>
</div>			

app/views/applicant_person_qualification_field_of_studies/show.html.erb
<p>
  <strong>Field of study:</strong>
  <%= @applicant_person_qualification_field_of_study.Field_Of_Study %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @applicant_person_qualification_field_of_study.Start_Date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @applicant_person_qualification_field_of_study.End_Date %>
</p>

<%= link_to 'Edit', edit_applicant_person_qualification_field_of_study_path(@applicant_person_qualification_field_of_study) %> |
<%= link_to 'Back', applicant_person_qualification_field_of_studies_path %>