config/routes.rb
Rails.application.routes.draw do
    devise_for :applicants
  resources :applicant_person_qualification_field_of_studies

    root :to => 'welcome#index'
  get 'applicants/index'
  get 'admin/main'
 get "admin/documents"
 get "admin/confirm"
 get "admin/DocumentsAdmin"
 get "documents/index"
  #get 'welcome/index'
  resources :applicant_emergency_contacts
  resources :applicant_disability_types
  resources :applicant_licenses
  resources :applicant_foi_programs
  resources :applicant_addresses
  resources :applicant_personal_details
  resources :applicant_field_of_studies
  resources :applicant_experiences
  resources :applicant_references

end

app/models/applicant_reference.rb
class ApplicantReference < ApplicationRecord
  belongs_to :applicant
  
  validates_format_of :Contact_Number,:with => /\A([0]{1})\d{9}\z/
  validates :Reference_Name, presence: true
  validates :Relationship, presence: true
  validates :applicant_id, presence: true
  validates_format_of :Email_address, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
end

app/controllers/applicant_references_controller.rb
class ApplicantReferencesController < ApplicationController
  before_action :set_applicant_reference, only: [:show, :edit, :update, :destroy]

  # GET /applicant_references
  # GET /applicant_references.json
  def index
    @applicant_references = current_applicant.applicant_references.all
  end

  # GET /applicant_references/1
  # GET /applicant_references/1.json
  def show
  end

  # GET /applicant_references/new
  def new
    @applicant_reference = current_applicant.applicant_references.build
  end

  # GET /applicant_references/1/edit
  def edit
  end

  # POST /applicant_references
  # POST /applicant_references.json
  def create
    @applicant_reference = current_applicant.applicant_references.build(applicant_reference_params)

    respond_to do |format|
      if @applicant_reference.save
        format.html { redirect_to applicant_references_url, notice: 'Applicant reference was successfully created.' }
        format.json { render :show, status: :created, location: @applicant_reference }
      else
        format.html { render :new }
        format.json { render json: @applicant_reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applicant_references/1
  # PATCH/PUT /applicant_references/1.json
  def update
    respond_to do |format|
      if @applicant_reference.update(applicant_reference_params)
        format.html { redirect_to applicant_references_url, notice: 'Applicant reference was successfully updated.' }
        format.json { render :show, status: :ok, location: @applicant_reference }
      else
        format.html { render :edit }
        format.json { render json: @applicant_reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applicant_references/1
  # DELETE /applicant_references/1.json
  def destroy
    @applicant_reference.destroy
    respond_to do |format|
      format.html { redirect_to applicant_references_url, notice: 'Applicant reference was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_applicant_reference
      @applicant_reference = ApplicantReference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def applicant_reference_params
      params.require(:applicant_reference).permit(:Contact_Number, :Reference_Name, :Email_address, :Relationship, :applicant_id)
    end
end

app/helpers/applicant_references_helper.rb
module ApplicantReferencesHelper
end

app/views/applicant_references/_form.html.erb
<%= simple_form_for(@applicant_reference) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :Reference_Name, label: "Reference Name", placeholder: "John" %>
    <%= f.input :Contact_Number, label: "Contact Number", placeholder: "0831234567" %>
    <%= f.input :Email_address, label: "Email Address", placeholder: "john@example.com" %>
    <%= f.input :Relationship, placeholder: "Manager" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Submit", class: "btn btn-block btn-primary" %><br>
  </div>
<% end %>

app/views/applicant_references/edit.html.erb
<div class="col-xs-12 col-md-8 col-md-offset-2">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h1 class="text-center">Edit <%= current_applicant.username %>'s Reference</h1>
		</div>
		<div class="panel-body">	
			<%= render 'form', applicant_reference: @applicant_reference %>
		</div>	
		<%= link_to 'Back', :back, class: "btn btn-xs btn-danger" %>
	</div>
</div>

app/views/applicant_references/index.html.erb
<div class="col-xs-12 col-md-8 col-md-offset-2">
  <% if !@applicant_references.any? %> 
    <%= render 'layouts/incomplete' %>
  <% end %>

  <div class="panel panel-primary">
    <div class="panel-heading">
      <h1 class="text-center"><%= current_applicant.username %>'s References</h1>
    </div>
    <div class="panel-body">

      <% @applicant_references.each do |applicant_reference| %>
        <div class="well text-center col-xs-12 col-md-8 col-md-offset-2">
          <h5 class="text-primary">Reference name: </h5><%= applicant_reference.Reference_Name %>
          <h5 class="text-primary">Contact number: </h5><%= applicant_reference.Contact_Number %>
          <h5 class="text-primary">Email address: </h5><%= applicant_reference.Email_address %>
          <h5 class="text-primary">Relationship: </h5><%= applicant_reference.Relationship %><hr>

          <%= link_to 'Edit Entry', edit_applicant_reference_path(applicant_reference), class: "btn btn-xs btn-warning" %>
          <%= link_to 'Delete Entry', applicant_reference, method: :delete, data: { confirm: 'Are you sure you want to delete this entry?' }, class: "btn btn-xs btn-danger" %>
        </div>
      <% end %>

      <br>
      <div class="col-xs-12 col-md-12">
        <%= link_to 'New Applicant Reference', new_applicant_reference_path, class: "btn btn-block btn-primary" %><br>
        <% if @applicant_references.any? %>
          <%= link_to 'Next Step', applicant_foi_programs_url, class: "btn btn-block btn-success" %>
        <% end %>
      </div>
    </div>
    <br><%= link_to 'Back', root_url, class: 'btn btn-xs btn-danger' %>  
  </div>
</div>

app/views/applicant_references/new.html.erb
<div class="col-xs-12 col-md-8 col-md-offset-2">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h1 class="text-center">New Reference</h1>
		</div>
		<div class="panel-body">	
			<%= render 'form', applicant_reference: @applicant_reference %>
		</div>	
		<%= link_to 'Back', :back, class: "btn btn-xs btn-danger" %>
	</div>
</div>

app/views/applicant_references/show.html.erb
<p>
  <strong>Contact number:</strong>
  <%= @applicant_reference.Contact_Number %>
</p>

<p>
  <strong>Reference name:</strong>
  <%= @applicant_reference.Reference_Name %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @applicant_reference.Email_address %>
</p>

<p>
  <strong>Relationship:</strong>
  <%= @applicant_reference.Relationship %>
</p>


<%= link_to 'Edit', edit_applicant_reference_path(@applicant_reference) %> |
<%= link_to 'Back', applicant_references_path %>