config/routes.rb
Rails.application.routes.draw do
    devise_for :applicants
  resources :applicant_person_qualification_field_of_studies

    root :to => 'welcome#index'
  get 'applicants/index'
  get 'admin/main'
 get "admin/documents"
 get "admin/confirm"
 get "admin/DocumentsAdmin"
 get "documents/index"
  #get 'welcome/index'
  resources :applicant_emergency_contacts
  resources :applicant_disability_types
  resources :applicant_licenses
  resources :applicant_foi_programs
  resources :applicant_addresses
  resources :applicant_personal_details
  resources :applicant_field_of_studies
  resources :applicant_experiences
  resources :applicant_references

end

app/models/applicant_personal_detail.rb
class ApplicantPersonalDetail < ApplicationRecord
  belongs_to :applicant
  belongs_to :applicant_race
  belongs_to :applicant_gender
  belongs_to :applicant_nationality
  belongs_to :applicant_marital_status
  belongs_to :applicant_current_occupation
  has_many:admin
  	validates_uniqueness_of :applicant_id

	validates :Surname, presence: true
	validates :First_Name, presence: true
	# validates :Middle_Name, presence: true
	validates_format_of :Contact_Number, :with => /\A([0]{1})\d{9}\z/
	validates :Contact_Number, presence: true
	validates_format_of :Alt_Contact_Number, :with => /\A([0]{1})\d{9}\z/
	validates :Alt_Contact_Number, presence: true
	validates :Criminal_Record, presence: true
	validates :Skills, presence: true
	validates :Application_Status, presence: true
	validates_format_of :Number_Of_Dependancies, presence: true, :with => /\A\d{1}\z/
	validates :applicant_id, presence: true
	validates :applicant_race_id, presence: true
	validates :applicant_gender_id, presence: true
	validates :applicant_marital_status_id, presence: true
	validates :applicant_nationality_id, presence: true
	validates :applicant_current_occupation_id, presence: true

end

app/controllers/applicant_personal_details_controller.rb
class ApplicantPersonalDetailsController < ApplicationController
  before_action :set_applicant_personal_detail, only: [:show, :edit, :update, :destroy]
  # @applicants = applicant_personal_details.all
  # GET /applicant_personal_details
  # GET /applicant_personal_details.json
  def index
    @applicant_personal_details = current_applicant.applicant_personal_details.all

  end

  # GET /applicant_personal_details/1
  # GET /applicant_personal_details/1.json
  def show
  end

  # GET /applicant_personal_details/new
  def new
    @applicant_personal_detail = current_applicant.applicant_personal_details.build
  end

  # GET /applicant_personal_details/1/edit
  def edit
  end

  # POST /applicant_personal_details
  # POST /applicant_personal_details.json
  def create
    @applicant_personal_detail = current_applicant.applicant_personal_details.build(applicant_personal_detail_params)

    respond_to do |format|
      if @applicant_personal_detail.save
        format.html { redirect_to applicant_personal_details_url, notice: 'Applicant personal detail was successfully created.' }
        format.json { render :show, status: :created, location: @applicant_personal_detail }
      else
        format.html { render :new }
        format.json { render json: @applicant_personal_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applicant_personal_details/1
  # PATCH/PUT /applicant_personal_details/1.json
  def update
    respond_to do |format|
      if @applicant_personal_detail.update(applicant_personal_detail_params)
        format.html { redirect_to applicant_personal_details_url, notice: 'Applicant personal detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @applicant_personal_detail }
      else
        format.html { render :edit }
        format.json { render json: @applicant_personal_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applicant_personal_details/1
  # DELETE /applicant_personal_details/1.json
  def destroy
    @applicant_personal_detail.destroy
    respond_to do |format|
      format.html { redirect_to applicant_personal_details_url, notice: 'Applicant personal detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_applicant_personal_detail
      @applicant_personal_detail = ApplicantPersonalDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def applicant_personal_detail_params
      params.require(:applicant_personal_detail).permit(:Surname, :First_Name, :Middle_Name,
       :Contact_Number, :Alt_Contact_Number, :Criminal_Record, :Skills,
        :Application_Status, :Number_Of_Dependancies, :applicant_id,
        :applicant_race_id, :applicant_gender_id, :applicant_marital_status_id,
        :applicant_nationality_id, :applicant_current_occupation_id)
    end
end

app/helpers/applicant_personal_details_helper.rb
module ApplicantPersonalDetailsHelper
end

app/views/applicant_personal_details/_form.html.erb
<%= simple_form_for @applicant_personal_detail do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs col-xs-8 col-xs-offset-2">
    <%= f.input :First_Name, label: "First Name", autofocus: true, placeholder: "John" %>
    <%= f.input :Middle_Name, label: "Middle Name", placeholder: "Michael" %>
    <%= f.input :Surname, placeholder: "Smith" %>
    <%= f.input :Contact_Number, label: "Contact Number", placeholder: "0831234567" %>
    <%= f.input :Alt_Contact_Number, label: "Alternate Contact Number", placeholder: "0837654321" %>
    <%= f.association :applicant_race, label: "Race", :label_method =>  lambda { |race| "#{race.Race}"  } %>
    <%= f.association :applicant_gender, label: "Gender", :label_method =>  lambda { |gender| "#{gender.Gender}"  } %>
    <%= f.association :applicant_nationality, label: "Nationality", :label_method => lambda { |nationality| "#{nationality.Nationality}"} %>
    <%= f.association :applicant_marital_status, label: "Marital Status", :label_method => lambda { |marital_status| "#{marital_status.Marital_Status}"} %>
    <%= f.input :Number_Of_Dependancies, label: "Number Of Dependancies", placeholder: "1, 2, 3, etc." %>
    <%= f.association :applicant_current_occupation, label: "Current Occupation Status", :label_method => lambda { |occupation| "#{occupation.Current_Occupation}"} %>
    <%= f.input :Skills, placeholder: "HTML, Bootstrap, Microsoft Office, Ruby on Rails, Project Management", hint: "Please specify 5 skills seperated by a comma" %>
    <%= f.input :Criminal_Record, label: "Criminal Record", as: :radio_buttons, :collection => [ ['Yes', 1], ['No', 0] ]  %>
    
    <%= f.hidden_field :Application_Status, value: 1 %>
  </div> 

  <div class="form-actions">
    <%= f.button :submit, "Submit", class: "btn btn-primary btn-block" %>
  </div>
<% end %><br>

app/views/applicant_personal_details/edit.html.erb
<div class="col-xs-12 col-md-8 col-md-offset-2">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h1 class="text-center">Edit <%= current_applicant.username %>'s Personal Details</h1>
		</div>
		<div class="panel-body">	
			<%= render 'form', applicant_personal_detail: @applicant_personal_detail %>
		</div>	
		<%= link_to 'Back', :back, class: "btn btn-xs btn-danger" %>
	</div>
</div>	

app/views/applicant_personal_details/index.html.erb
<div class="col-xs-12 col-md-8 col-md-offset-2">
  <% if !@applicant_personal_details.any? %> 
    <%= render 'layouts/incomplete' %>
  <% end %>
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h1 class="text-center"><%= current_applicant.username %>'s Personal Details</h1>
    </div>
    <div class="panel-body">
       
      <% @applicant_personal_details.each do |applicant_personal_detail| %>
        <div class="well col-xs-12 col-md-8 col-md-offset-2 text-center">
          <h5 class="text-primary">Surname: </h5><%= applicant_personal_detail.Surname %><br>
          <h5 class="text-primary">First Name: </h5><%= applicant_personal_detail.First_Name %><br>
          <h5 class="text-primary">Middle Name: </h5>
            <% if applicant_personal_detail.Middle_Name.blank? %>
              [N/A]
            <% else %>
              <%= applicant_personal_detail.Middle_Name %> 
            <% end %>
          
          <br>
          <h5 class="text-primary">Contact Number: </h5><%= applicant_personal_detail.Contact_Number %><br>
          <h5 class="text-primary">Alternate Number: </h5><%= applicant_personal_detail.Alt_Contact_Number %><br>
          <h5 class="text-primary">Criminal Record: </h5><%= applicant_personal_detail.Criminal_Record %><br>
          <h5 class="text-primary">Current Occupation: </h5><%= applicant_personal_detail.applicant_current_occupation %><br>
          <h5 class="text-primary">Skills: </h5><%= applicant_personal_detail.Skills %><br>
          <!-- <h5 class="text-primary">Application Status: </h5><%= applicant_personal_detail.Application_Status %><br> -->
          <h5 class="text-primary">Number Of Dependancies: </h5><%= applicant_personal_detail.Number_Of_Dependancies %><br>
          <h5 class="text-primary">Race: </h5><%= applicant_personal_detail.applicant_race %><br>
          <h5 class="text-primary">Gender: </h5><%= applicant_personal_detail.applicant_gender %><br>
          <h5 class="text-primary">Marital Status: </h5><%= applicant_personal_detail.applicant_marital_status %><br>
          <h5 class="text-primary">Nationality: </h5><%= applicant_personal_detail.applicant_nationality %><hr>
              
          <%= link_to 'Edit Entry', edit_applicant_personal_detail_path(applicant_personal_detail), class: "btn btn-xs btn-warning" %>
          <%= link_to 'Delete Entry', applicant_personal_detail, method: :delete, data: { confirm: 'Are you sure you want to delete this entry?' }, class: "btn btn-xs btn-danger" %>
        </div>  
      <% end %>
      
    
      <br>
      <div class="col-xs-12 col-md-12">
        <% if !@applicant_personal_details.any? %>
          <%= link_to 'New Applicant Personal Detail', new_applicant_personal_detail_path, id: "applicant_personal_details", class: "btn btn-primary btn-block" %>
        <% else %>
          <%= link_to 'Next Step', new_applicant_address_url, class: "btn btn-success btn-block" %>
        <% end %>
      </div>

    </div>
    <br><%= link_to 'Back', root_url, class: 'btn btn-xs btn-danger' %>
  </div>
</div>

app/views/applicant_personal_details/new.html.erb
<div class="col-xs-12 col-md-8 col-md-offset-2">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h1 class="text-center">Add <%= current_applicant.username %>'s Personal Details</h1>
		</div>
		<div class="panel-body">	
			<%= render 'form', applicant_personal_detail: @applicant_personal_detail %>
		</div>	
		<%= link_to 'Back', :back, class: "btn btn-xs btn-danger" %>
	</div>
</div>

app/views/applicant_personal_details/new.js.erb
$('#applicant_personal_details').hide().after('<%= j render("form") %>');

app/views/applicant_personal_details/show.html.erb
<p>
  <strong>Surname:</strong>
  <%= @applicant_personal_detail.Surname %>
</p>

<p>
  <strong>First name:</strong>
  <%= @applicant_personal_detail.First_Name %>
</p>

<p>
  <strong>Middle name:</strong>
  <%= @applicant_personal_detail.Middle_Name %>
</p>

<p>
  <strong>Contact number:</strong>
  <%= @applicant_personal_detail.Contact_Number %>
</p>

<p>
  <strong>Alt contact number:</strong>
  <%= @applicant_personal_detail.Alt_Contact_Number %>
</p>

<p>
  <strong>Criminal record:</strong>
  <%= @applicant_personal_detail.Criminal_Record %>
</p>

<p>
  <strong>Skills:</strong>
  <%= @applicant_personal_detail.Skills %>
</p>

<p>
  <strong>Application status:</strong>
  <%= @applicant_personal_detail.Application_Status %>
</p>

<p>
  <strong>Number of dependancies:</strong>
  <%= @applicant_personal_detail.Number_Of_Dependancies %>
</p>


<%= link_to 'Edit', edit_applicant_personal_detail_path(@applicant_personal_detail) %> |
<%= link_to 'Back', applicant_personal_details_path %>