config/routes.rb
Rails.application.routes.draw do
    devise_for :applicants
  resources :applicant_person_qualification_field_of_studies

    root :to => 'welcome#index'
  get 'applicants/index'
  get 'admin/main'
 get "admin/documents"
 get "admin/confirm"
 get "admin/DocumentsAdmin"
 get "documents/index"
  #get 'welcome/index'
  resources :applicant_emergency_contacts
  resources :applicant_disability_types
  resources :applicant_licenses
  resources :applicant_foi_programs
  resources :applicant_addresses
  resources :applicant_personal_details
  resources :applicant_field_of_studies
  resources :applicant_experiences
  resources :applicant_references

end

app/models/applicant_emergency_contact.rb
class ApplicantEmergencyContact < ApplicationRecord
  belongs_to :applicant

  validates_format_of :Emergency_Contact_Number,:with => /\A([0]{1})\d{9}\z/
  validates :Emergency_Contact_Name, presence: true
  validates :Emergency_Contact_Number, presence: true
  validates :Emergency_Contact_Relationship, presence: true	
end

app/controllers/applicant_emergency_contacts_controller.rb
class ApplicantEmergencyContactsController < ApplicationController
  before_action :set_applicant_emergency_contact, only: [:show, :edit, :update, :destroy]

  # GET /applicant_emergency_contacts
  # GET /applicant_emergency_contacts.json
  def index
    @applicant_emergency_contacts = current_applicant.applicant_emergency_contacts.all
  end

  # GET /applicant_emergency_contacts/1
  # GET /applicant_emergency_contacts/1.json
  def show
  end

  # GET /applicant_emergency_contacts/new
  def new
    @applicant_emergency_contact = current_applicant.applicant_emergency_contacts.build
  end

  # GET /applicant_emergency_contacts/1/edit
  def edit
  end

  # POST /applicant_emergency_contacts
  # POST /applicant_emergency_contacts.json
  def create
    @applicant_emergency_contact = current_applicant.applicant_emergency_contacts.build(applicant_emergency_contact_params)

    respond_to do |format|
      if @applicant_emergency_contact.save
        format.html { redirect_to applicant_emergency_contacts_url, notice: 'Applicant emergency contact was successfully created.' }
        format.json { render :show, status: :created, location: @applicant_emergency_contact }
      else
        format.html { render :new }
        format.json { render json: @applicant_emergency_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applicant_emergency_contacts/1
  # PATCH/PUT /applicant_emergency_contacts/1.json
  def update
    respond_to do |format|
      if @applicant_emergency_contact.update(applicant_emergency_contact_params)
        format.html { redirect_to applicant_emergency_contacts_url, notice: 'Applicant emergency contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @applicant_emergency_contact }
      else
        format.html { render :edit }
        format.json { render json: @applicant_emergency_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applicant_emergency_contacts/1
  # DELETE /applicant_emergency_contacts/1.json
  def destroy
    @applicant_emergency_contact.destroy
    respond_to do |format|
      format.html { redirect_to applicant_emergency_contacts_url, notice: 'Applicant emergency contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_applicant_emergency_contact
      @applicant_emergency_contact = ApplicantEmergencyContact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def applicant_emergency_contact_params
      params.require(:applicant_emergency_contact).permit(:Emergency_Contact_Name, :Emergency_Contact_Number, :Emergency_Contact_Relationship, :applicant_id)
    end
end

app/helpers/applicant_emergency_contacts_helper.rb
module ApplicantEmergencyContactsHelper
end

app/views/applicant_emergency_contacts/_form.html.erb
<%= simple_form_for(@applicant_emergency_contact) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :Emergency_Contact_Name, label: "Name", placeholder: "John" %>
    <%= f.input :Emergency_Contact_Number, label: "Contact Number", placeholder: "0831234567" %>
    <%= f.input :Emergency_Contact_Relationship, label: "Relationship", placeholder: "Father" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Submit", class: "btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/applicant_emergency_contacts/edit.html.erb
<div class="col-xs-12 col-md-8 col-md-offset-2">
  <div class="panel panel-primary">
    <div class="panel-heading">
	  <h1 class="text-center">Edit <%= current_applicant.username %> Emergency Contact</h1>
	</div>  
	<div class="panel-body">  
	  <%= render 'form', applicant_emergency_contact: @applicant_emergency_contact %>
    </div>
	<%= link_to 'Back', :back, class: "btn btn-xs btn-danger" %>
  </div>
</div>

app/views/applicant_emergency_contacts/index.html.erb
<div class="col-xs-12 col-md-8 col-md-offset-2">
  <% if !@applicant_emergency_contacts.any? %> 
    <%= render 'layouts/incomplete' %>
  <% end %>

  <div class="panel panel-primary">
    <div class="panel-heading">
      <h1 class="text-center"><%= current_applicant.username %>'s Emergency Contacts</h1>
    </div>
    <div class="panel-body">

      <% @applicant_emergency_contacts.each do |applicant_emergency_contact| %>
        <div class="well col-xs-12 col-md-8 col-md-offset-2 text-center">
          <h5 class="text-primary">Emergency contact name </h5> <%= applicant_emergency_contact.Emergency_Contact_Name %>
          <h5 class="text-primary">Emergency contact number </h5> <%= applicant_emergency_contact.Emergency_Contact_Number %>
          <h5 class="text-primary">Emergency contact relationship </h5> <%= applicant_emergency_contact.Emergency_Contact_Relationship %><hr>
          <%= link_to 'Edit', edit_applicant_emergency_contact_path(applicant_emergency_contact), class: "btn btn-xs btn-warning" %>
          <%= link_to 'Destroy', applicant_emergency_contact, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger" %>
        </div>  
      <% end %>

      <br>

      <div class="col-xs-12 col-md-12">
        <%= link_to 'New Emergency Contact', new_applicant_emergency_contact_path, class: "btn btn-primary btn-block" %><br>
        <% if @applicant_emergency_contacts.any? %>
          <%= link_to 'Next Step', applicant_person_qualification_field_of_studies_url, class: "btn btn-block btn-success" %>
        <% end %>
      </div>

      
    </div>
    <br><%= link_to 'Back', root_url, class: 'btn btn-xs btn-danger' %>
  </div>
</div>

app/views/applicant_emergency_contacts/new.html.erb
<div class="col-xs-12 col-md-8 col-md-offset-2">
  <div class="panel panel-primary">
    <div class="panel-heading">
	  <h1 class="text-center">New Emergency Contact</h1>
	</div>
	<div class="panel-body">  
	  <%= render 'form', applicant_emergency_contact: @applicant_emergency_contact %>
	</div>	
    <%= link_to 'Back', :back, class: "btn btn-xs btn-danger" %>
  </div>
</div>  

app/views/applicant_emergency_contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Emergency contact name:</strong>
  <%= @applicant_emergency_contact.Emergency_Contact_Name %>
</p>

<p>
  <strong>Emergency contact number:</strong>
  <%= @applicant_emergency_contact.Emergency_Contact_Number %>
</p>

<p>
  <strong>Emergency contact relationship:</strong>
  <%= @applicant_emergency_contact.Emergency_Contact_Relationship %>
</p>

<p>
  <strong>Applicant:</strong>
  <%= @applicant_emergency_contact.applicant %>
</p>

<%= link_to 'Edit', edit_applicant_emergency_contact_path(@applicant_emergency_contact) %> |
<%= link_to 'Back', applicant_emergency_contacts_path %>